qatrack/api/parts/urls.py
from django.conf.urls import include, url
from rest_framework import routers

from qatrack.api.parts import views

router = routers.DefaultRouter()
router.register(r'suppliers', views.SupplierViewSet)
router.register(r'storages', views.StorageViewSet)
router.register(r'partcategories', views.PartCategoryViewSet)
router.register(r'parts', views.PartViewSet)
router.register(r'partstoragecollections', views.PartStorageCollectionViewSet)
router.register(r'partsuppliercollections', views.PartSupplierCollectionViewSet)
router.register(r'partuseds', views.PartUsedViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
]

qatrack/parts/urls.py
from django.conf.urls import include, url

from qatrack.parts import views

urlpatterns = [
    url(r'^parts_searcher$', views.parts_searcher, name='parts_searcher'),
    url(r'^parts_storage_searcher$', views.parts_storage_searcher, name='parts_storage_searcher'),
    url(r'^room_location_searcher$', views.room_location_searcher, name='room_location_searcher'),
    url(r'^list(?:/(?P<f>\S+))?/$', views.PartsList.as_view(), name='parts_list'),
    url(r'^new/$', views.PartUpdateCreate.as_view(), name='part_new'),
    url(r'^edit/(?P<pk>\d+)?$', views.PartUpdateCreate.as_view(), name='part_edit'),
    url(r'^details/(?P<pk>\d+)?$', views.PartDetails.as_view(), name='part_details'),
    url(r'^suppliers/$', views.SuppliersList.as_view(), name='suppliers_list'),
]

qatrack/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.templatetags.staticfiles import static as static_url
from django.views.generic.base import RedirectView, TemplateView


admin.autodiscover()


favicon_view = RedirectView.as_view(url=static_url("qatrack_core/img/favicon.ico"), permanent=True)
touch_view = RedirectView.as_view(url=static_url("qatrack_core/img/apple-touch-icon.png"), permanent=True)


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="homepage.html"), name="home"),
    url(r'^accounts/', include('qatrack.accounts.urls')),
    url(r'^qa/', include('qatrack.qa.urls')),
    url(r'^units/', include('qatrack.units.urls')),
    url(r'^core/', include('qatrack.qatrack_core.urls')),
    url(r'^dashboard/',include('qatrack.dashboard.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^favicon\.ico$', favicon_view),
    url(r'^apple-touch-icon\.png$', touch_view),

    # third party
    url(r'^', include('genericdropdown.urls')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^admin/dynamic_raw_id/', include('dynamic_raw_id.urls')),
    url(r'^api/', include('qatrack.api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.USE_SERVICE_LOG:
    urlpatterns += [url(r'^servicelog/', include('qatrack.service_log.urls'))]

if settings.USE_PARTS:
    urlpatterns += [url(r'^parts/', include('qatrack.parts.urls'))]

if settings.USE_ISSUES:
    urlpatterns += [url(r'^issues/', include('qatrack.issue_tracker.urls'))]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

qatrack/parts/models.py
from decimal import Decimal
from django.core.validators import MinValueValidator
from django.db import models
from django.utils.translation import ugettext as _

from qatrack.units import models as u_models
from qatrack.service_log import models as sl_models


class Supplier(models.Model):

    name = models.CharField(max_length=32, unique=True)
    notes = models.TextField(
        max_length=255, blank=True, null=True, help_text=_('Additional comments about this supplier')
    )

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class RoomManager(models.Manager):

    def get_queryset(self):
        return super(RoomManager, self).get_queryset().select_related('site')


class Room(models.Model):

    site = models.ForeignKey(u_models.Site, blank=True, null=True, help_text=_('Site this storage room is located'))
    name = models.CharField(max_length=32, help_text=_('Name of room or room number'))

    objects = RoomManager()

    class Meta:
        ordering = ['site', 'name']
        unique_together = ['site', 'name']

    def __str__(self):
        return '%s%s' % (self.name, ' (%s)' % self.site.name if self.site else '')

    def save(self, *args, **kwargs):
        new = self.pk is None
        super().save(*args, **kwargs)
        if new:
            # Create generic storage (ie, no location)
            Storage.objects.create(room=self)


class StorageManager(models.Manager):

    def get_queryset(self):
        return super(StorageManager, self).get_queryset().select_related('room', 'room__site').order_by('location')

    def get_queryset_for_room(self, room):
        return super().get_queryset().filter(room=room).order_by('location')


class Storage(models.Model):

    room = models.ForeignKey(Room, blank=True, null=True, help_text=_('Room for part storage'), on_delete=models.CASCADE)

    location = models.CharField(max_length=32, blank=True, null=True)
    description = models.TextField(max_length=255, null=True, blank=True)

    objects = StorageManager()

    class Meta:
        verbose_name_plural = 'Storage'
        unique_together = ['room', 'location']

    def __str__(self):
        items = []
        if self.room:
            if self.room.site:
                items.append(self.room.site.name)
            items.append(self.room.name)
        if self.location:
            items.append(self.location)
        else:
            items.append('<no location>')

        return ' - '.join(items)


class PartCategory(models.Model):

    name = models.CharField(max_length=64)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Part(models.Model):

    name = models.CharField(help_text=_('Brief name describing this part'), max_length=255)
    part_category = models.ForeignKey(PartCategory, blank=True, null=True)
    suppliers = models.ManyToManyField(
        Supplier, blank=True, help_text=_('Suppliers of this part'), related_name='parts',
        through='PartSupplierCollection'
    )
    storage = models.ManyToManyField(
        Storage, through='PartStorageCollection', related_name='parts', help_text=_('Storage locations for this part')
    )

    part_number = models.CharField(max_length=32, unique=True)
    alt_part_number = models.CharField(
        max_length=32, blank=True, null=True, verbose_name=_('Alternate part number')
    )
    quantity_min = models.PositiveIntegerField(
        default=0, help_text=_('Notify when the quantity of this part in storage falls below this number'),
    )
    quantity_current = models.PositiveIntegerField(help_text=_('The number of parts in storage currently'), default=0, editable=False)
    cost = models.DecimalField(
        default=0, decimal_places=2, max_digits=10, help_text=_('Cost of this part'), null=True, blank=True,
        validators=[MinValueValidator(Decimal('0.00'))]
    )
    notes = models.TextField(max_length=255, blank=True, null=True, help_text=_('Additional comments about this part'))
    is_obsolete = models.BooleanField(default=False, help_text=_('Is this part now obsolete?'))

    class Meta:
        permissions = (('view_part', 'Can View Part'),)
        ordering = ['part_number']

    def __str__(self):
        return '%s%s - %s' % (self.part_number, ' (%s)' % self.alt_part_number if self.alt_part_number else '', self.name)

    def set_quantity_current(self):
        qs = PartStorageCollection.objects.filter(part=self, storage__isnull=False)
        if qs.exists():
            self.quantity_current = qs.aggregate(models.Sum('quantity'))['quantity__sum']
        else:
            self.quantity_current = 0
        self.quantity_current = self.quantity_current if self.quantity_current >= 0 else 0
        self.save()
        return self.quantity_current < self.quantity_min


class PartStorageCollectionManager(models.Manager):

    def get_queryset(self):
        return super(PartStorageCollectionManager, self).get_queryset().select_related(
            'storage', 'part', 'storage__room', 'storage__room__site'
        ).order_by(
            '-quantity',
            'part__part_number'
        )


class PartStorageCollection(models.Model):

    part = models.ForeignKey(Part)
    storage = models.ForeignKey(Storage)

    quantity = models.IntegerField()

    objects = PartStorageCollectionManager()

    class Meta:
        unique_together = ('part', 'storage')
        default_permissions = ()

    def save(self, *args, **kwargs):
        self.quantity = self.quantity if self.quantity >= 0 else 0
        super(PartStorageCollection, self).save(*args, **kwargs)
        self.part.set_quantity_current()

    def __str__(self):
        locs = []
        if self.storage.room.site:
            locs.append(self.storage.room.site.name)
        locs.append(self.storage.room.name)
        if self.storage.location:
            locs.append(self.storage.location)
        locs.append('(%s)' % self.quantity)
        return ' - '.join(locs)


class PartSupplierCollection(models.Model):

    part = models.ForeignKey(Part, on_delete=models.CASCADE)
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE)
    part_number = models.CharField(
        max_length=32, null=True, blank=True,
        help_text=_('Does this supplier have a different part number for this part')
    )

    class Meta:
        unique_together = ('part', 'supplier')
        default_permissions = ()


class PartUsed(models.Model):

    service_event = models.ForeignKey(sl_models.ServiceEvent, on_delete=models.CASCADE)
    part = models.ForeignKey(Part, help_text=_('Select the part used'), on_delete=models.CASCADE)
    from_storage = models.ForeignKey(Storage, null=True, blank=True, on_delete=models.SET_NULL)

    quantity = models.IntegerField()

    def add_back_to_storage(self):

        if self.from_storage:
            try:
                psc = PartStorageCollection.objects.get(part=self.part, storage=self.from_storage)
                psc.quantity += self.quantity
                psc.save()
            except PartStorageCollection.DoesNotExist:
                PartStorageCollection.objects.create(part=self.part, storage=self.from_storage, quantity=self.quantity)

    def remove_from_storage(self):

        if self.from_storage:
            try:
                psc = PartStorageCollection.objects.get(part=self.part, storage=self.from_storage)
                psc.quantity -= self.quantity
                psc.save()
            except PartStorageCollection.DoesNotExist:
                pass

qatrack/api/parts/views.py
from rest_framework import viewsets
from rest_framework.filters import OrderingFilter
from rest_framework_filters import backends

from qatrack.api.parts import filters, serializers
from qatrack.parts import models


class SupplierViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = models.Supplier.objects.all()
    serializer_class = serializers.SupplierSerializer
    filter_class = filters.SupplierFilter
    filter_backends = (backends.DjangoFilterBackend, OrderingFilter,)


class StorageViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = models.Storage.objects.all()
    serializer_class = serializers.StorageSerializer
    filter_class = filters.StorageFilter
    filter_backends = (backends.DjangoFilterBackend, OrderingFilter,)


class PartCategoryViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = models.PartCategory.objects.all()
    serializer_class = serializers.PartCategorySerializer
    filter_class = filters.PartCategoryFilter
    filter_backends = (backends.DjangoFilterBackend, OrderingFilter,)


class PartViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = models.Part.objects.all()
    serializer_class = serializers.PartSerializer
    filter_class = filters.PartFilter
    filter_backends = (backends.DjangoFilterBackend, OrderingFilter,)


class PartStorageCollectionViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = models.PartStorageCollection.objects.all()
    serializer_class = serializers.PartStorageCollectionSerializer
    filter_class = filters.PartStorageCollectionFilter
    filter_backends = (backends.DjangoFilterBackend, OrderingFilter,)


class PartSupplierCollectionViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = models.PartSupplierCollection.objects.all()
    serializer_class = serializers.PartSupplierCollectionSerializer
    filter_class = filters.PartSupplierCollectionFilter
    filter_backends = (backends.DjangoFilterBackend, OrderingFilter,)


class PartUsedViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = models.PartUsed.objects.all()
    serializer_class = serializers.PartUsedSerializer
    filter_class = filters.PartUsedFilter
    filter_backends = (backends.DjangoFilterBackend, OrderingFilter,)

qatrack/parts/templates/parts/part_details.html
{% extends "service_log/sl_base.html" %}

{% load widget_tweaks %}
{% load qa_tags %}

{% block head_title %}Part{% endblock %}

{% block extra_css %}
    {{ block.super }}
{% endblock extra_css %}

{% block extra_js %}
    <script type="text/javascript">

    </script>
{% endblock extra_js %}

{% block require_javascript %}
{#    require(['p_part', 'sidebar']);#}
{% endblock require_javascript %}

{% block body %}

    <div>

    </div>

    <form action="" method="post" novalidate>
        {% csrf_token %}
        <div class="max-width-lg">
            <div class="row">
                <div class="col-md-3">
                    <h3 class="no-margin-top">Part {{ part.id }} Details</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="box">
                        <div class="box-header">

                        </div>
                        <div class="box-body">
                            <div class="row">
                                <div class="col-sm-6">
                                    <dl class="dl-horizontal">
                                        <dt>Part number:</dt><dd><div>{{ part.part_number }}</div></dd>
                                        <dt>Cost:</dt><dd><div>{{ part.cost }}</div></dd>
                                        <dt>Quantity min:</dt><dd><div>{{ part.quantity_min }}</div></dd>
                                        <dt>Quantity current:</dt><dd><div>{{ part.quantity_current }}</div></dd>
                                    </dl>


                                </div>
                                <div class="col-sm-6">
                                    <dl class="dl-horizontal">
                                        <dt>Alternate Part number:</dt><dd><div>{{ part.alt_part_number }}</div></dd>
                                        <dt>Part category:</dt><dd><div>{% if part.part_category %}{{ part.part_category }}{% endif %}</div></dd>
                                        <dt>Obsolete:</dt><dd><div>{{ part.is_obsolete }}</div></dd>
                                    </dl>

                                </div>

                            </div>
                            <div class="row display-flex">
                                <div class="col-md-6">
                                    {% spaceless %}
                                    <dl class="height-100 margin-0">
                                        <dt>Name:</dt>
                                        <dd class="text-display pre height-100-40">{{ part.name }}</dd>
                                    </dl>{% endspaceless %}
                                </div>
                                <div class="col-md-6">
                                    {% if part.notes %}{% spaceless %}
                                    <dl class="height-100 margin-0">
                                        <dt>Notes:</dt>
                                        <dd class="text-display pre height-100-40">{{ part.notes }}</dd>
                                    </dl>{% endspaceless %}
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                {% with part.partsuppliercollection_set.all as psc_set %}
                    <div class="col-md-5">
                        {% if psc_set|length > 0 %}
                            <div class="box">
                                <div class="box-header">
                                    <h4 class="box-title">Suppliers</h4>
                                </div>

                                <div class="box-body">
                                    <table class="table table-condensed table-hover">
                                        <thead>
                                            <tr>
                                                <th>Supplier</th>
                                                <th>Supplier Specific Part #</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for psc in psc_set %}
                                                <tr>
                                                    <td class="min-width-200">{{ psc.supplier.name }}</td>
                                                    <td>{% if psc.part_number %}{{ psc.part_number }}{% endif %}</td>
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                        <tfoot>

                                        </tfoot>
                                    </table>
                                </div>

                            </div>
                        {% endif %}

                    </div>
                {% endwith %}
                {% with part.partstoragecollection_set.all as psc_set %}
                    <div class="col-md-7">
                        {% if psc_set|length > 0 %}
                            <div class="box">
                                <div class="box-header">
                                    <h4 class="box-title">Storage</h4>
                                </div>

                                <div class="box-body">
                                    <table class="table table-condensed table-hover">
                                        <thead>
                                            <tr>
                                                <th>Room</th>
                                                <th>Location</th>
                                                <th class="max-width-75">Quantity</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for psc in psc_set %}
                                                <tr title="{{ psc.storage.description }}">
                                                    <td class="min-width-150 room-td">{{ psc.storage.room }}</td>
                                                    <td class="min-width-100">{{ psc.storage.location }}</td>
                                                    <td class="max-width-75">{{ psc.quantity }}</td>
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                        <tfoot>

                                        </tfoot>
                                    </table>
                                </div>

                            </div>
                        {% endif %}

                    </div>
                {% endwith %}
            </div>

            <div class="row">
                <div class="col-md-12">
                    {% if perms.parts.change_part %}
                        <a href="{% url 'part_edit' part.id %}" class="btn btn-flat btn-default pull-right">Edit</a>
                    {% endif %}
                </div>
            </div>
        </div>




    </form>
{% endblock body %}

qatrack/parts/templates/parts/parts_list.html
{% extends "site_base.html" %}

{% load qa_tags %}
{% load listable %}

{% block head_title %}{{page_title}}{% endblock %}

{% block extra_css %}
    {{ block.super }}
    <link href="{{ STATIC_URL }}datepicker/css/bootstrap-datepicker.min.css?v={{VERSION}}" rel="stylesheet">
    <link href="{{ STATIC_URL }}multiselect/css/bootstrap.multiselect.css?v={{VERSION}}" rel="stylesheet">
    <link href="{{ STATIC_URL }}daterangepicker/css/daterangepicker.css?v={{VERSION}}" rel="stylesheet">
    <link href="{{ STATIC_URL }}qatrack_core/css/tables.css?v={{VERSION}}" rel="stylesheet">
    <link href="{{ STATIC_URL }}qatrack_core/css/custom-daterangepicker.css?v={{VERSION}}" rel="stylesheet">
{% endblock extra_css %}

{% block extra_js %}
    {% autoescape off %}
        {% listable view_name dom="<'row'<'col-sm-5'i><'col-sm-7'p>><'row'<'col-sm-12'tr>><'row'<'col-sm-5'><'col-sm-7'p>>" requirejs=True pagination_type='bootstrap3' css_table_class='table-hover table-condensed table-custom-listable' css_input_class='btn-flat btn-sm input-sm full-width' auto_width=False %}
    {% endautoescape %}
{% endblock %}

{% block require_javascript %}
    require(['listable']);
{% endblock require_javascript %}

{% block body %}

    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header">
                    <i class="fa {{ icon }} fa-fw" aria-hidden="true"></i>
                    <h3 class="box-title">{{page_title}}</h3>

                </div>
                <div class="box-body pad">
                    {{ listable_table }}
                </div>
            </div>
        </div>
    </div>

{% endblock body %}

qatrack/parts/templates/parts/parts_units_cost.html
{% extends "site_base.html" %}

{% load qa_tags %}

{% block head_title %}Units Parts Cost{% endblock %}

{% block extra_css %}
    <link href="{{ STATIC_URL }}qa/css/qa.css?v={{ VERSION }}" rel="stylesheet">
    <link href="{{ STATIC_URL }}daterangepicker/css/daterangepicker.css?v={{ VERSION }}" rel="stylesheet">
    <link href="{{ STATIC_URL }}qatrack_core/css/custom-daterangepicker.css?v={{ VERSION }}" rel="stylesheet">
    <link href="{{ STATIC_URL }}select2/css/select2.min.css?v={{ VERSION }}" rel="stylesheet">
    <link href="{{ STATIC_URL }}qatrack_core/css/custom-select2.css?v={{ VERSION }}" rel="stylesheet">
    <link href="{{ STATIC_URL }}felter/css/felter.css?v={{ VERSION }}" rel="stylesheet">
{% endblock extra_css %}

{% block require_javascript %}
    require(['parts_reporting']);
{% endblock require_javascript %}

{% block body_class %}layout-top-nav{% endblock body_class %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">
                        <i class="fa fa-cubes" aria-hidden="true"></i>
                        Parts Cost For Units
                    </h3>
                </div>
                <div class="box-body">

                    <form id="unit_area_type" action="{% url 'go_units_parts_cost' %}" method="get">
                        <div class="row">
                            <div class="col-md-12 form-horizontal">
                                <div class="form-group row">
                                    <div class="col-md-1"></div>
                                    <div class="col-md-10">
                                        <div class="row">
                                            <label for="date_range_selector" class="col-md-2 control-label">Date Range:</label>
                                            <div class="col-md-10"><input id="date_range_selector" class="form-control" name="date_range"></div>
                                        </div>
                                    </div>
                                    <div class="col-md-1"></div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-md-1"></div>
                                    <div class="col-md-10">
                                        <select name="units" id="units" multiple class="form-control">
                                            {% for u in units %}
                                                <option data-active="{{ u.active }}" value="{{ u.pk }}" selected>{{ u.name }}</option>
                                            {% endfor %}
                                        </select>
                                        <select name="service_areas" id="service_areas" multiple class="form-control">
                                            {% for sa in service_areas %}
                                                <option value="{{ sa.pk }}" selected>{{ sa.name }}</option>
                                            {% endfor %}
                                        </select>
                                        <select name="service_types" id="service_types" multiple class="form-control">
                                            {% for st in service_types %}
                                                <option value="{{ st.pk }}" selected>{{ st.name }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                    <div class="col-md-1"></div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <input id="go_units_parts" class="btn btn-flat btn-info" value="Generate Summary Report" type="submit">
    {#                            <div id="go_units_parts_detailed" class="btn btn-flat btn-info">Generate Detailed Report(s)</div>#}
                            </div>
                        </div>
                    </form>

                </div>
                <div class="box-footer">

                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">

        </div>
    </div>
{% endblock body %}

qatrack/parts/templates/parts/table_context_p_actions.html
{% load qa_tags %}
<div style="min-width: 85px;">
    {% if perms.parts.change_part %}
        <a class="btn btn-default btn-xs btn-flat"
          href="{% url 'part_edit' p.pk %}{% if next %}?next={{ next }}{% endif %}"
          title="Edit details of {{ p.name }}"
        >Edit</a>
    {% endif %}
    {% if perms.parts.view_part %}
        <a class="btn btn-default btn-xs btn-flat"
          href="{% url 'part_details' p.pk %}{% if next %}?next={{ next }}{% endif %}"
          title="View details of {{ p.name }}"
          >
          Details
        </a>
    {% endif %}
</div>

qatrack/parts/templates/parts/table_context_suppliers_actions.html
{% load qa_tags %}
{#<div style="min-width: 85px;">#}
{#    <a class="btn btn-primary btn-xs btn-flat" href="{% url 'part_edit' p.pk %}{% if next %}?next={{ next }}{% endif %}">Edit</a>#}
{#</div>#}
TODO