qatrack/issue_tracker/urls.py
from django.conf.urls import url
from qatrack.issue_tracker import views

urlpatterns = [
    url(r'^issue/new/$', views.IssueCreate.as_view(), name='issue_new'),
    url(r'^issue/details/(?P<pk>\d+)?$', views.IssueDetails.as_view(), name='issue_details'),
    url(r'^issues/$', views.IssueList.as_view(), name='issue_list'),
]

qatrack/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.templatetags.staticfiles import static as static_url
from django.views.generic.base import RedirectView, TemplateView


admin.autodiscover()


favicon_view = RedirectView.as_view(url=static_url("qatrack_core/img/favicon.ico"), permanent=True)
touch_view = RedirectView.as_view(url=static_url("qatrack_core/img/apple-touch-icon.png"), permanent=True)


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="homepage.html"), name="home"),
    url(r'^accounts/', include('qatrack.accounts.urls')),
    url(r'^qa/', include('qatrack.qa.urls')),
    url(r'^units/', include('qatrack.units.urls')),
    url(r'^core/', include('qatrack.qatrack_core.urls')),
    url(r'^dashboard/',include('qatrack.dashboard.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^favicon\.ico$', favicon_view),
    url(r'^apple-touch-icon\.png$', touch_view),

    # third party
    url(r'^', include('genericdropdown.urls')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^admin/dynamic_raw_id/', include('dynamic_raw_id.urls')),
    url(r'^api/', include('qatrack.api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.USE_SERVICE_LOG:
    urlpatterns += [url(r'^servicelog/', include('qatrack.service_log.urls'))]

if settings.USE_PARTS:
    urlpatterns += [url(r'^parts/', include('qatrack.parts.urls'))]

if settings.USE_ISSUES:
    urlpatterns += [url(r'^issues/', include('qatrack.issue_tracker.urls'))]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

qatrack/issue_tracker/models.py
import re

from django.core.validators import RegexValidator
from django.db import models
from django.contrib.auth.models import User

re_255 = '([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])'
color_re = re.compile('^rgba\(' + re_255 + ',' + re_255 + ',' + re_255 + ',(0(\.[0-9][0-9]?)?|1)\)$')
validate_color = RegexValidator(color_re, 'Enter a valid color.', 'invalid')


class IssueType(models.Model):

    name = models.CharField(max_length=32)

    def __str__(self):
        return self.name


class IssuePriority(models.Model):

    name = models.CharField(max_length=32)
    colour = models.CharField(max_length=22, validators=[validate_color], blank=True, null=True)
    order = models.PositiveIntegerField(default=0)

    class Meta:
        verbose_name_plural = 'Priorities'
        ordering = ['order']

    def __str__(self):
        return self.name


class IssueTag(models.Model):

    name = models.CharField(max_length=32)
    description = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class IssueStatus(models.Model):

    name = models.CharField(max_length=32)
    description = models.CharField(max_length=255, null=True, blank=True)
    colour = models.CharField(max_length=22, validators=[validate_color], blank=True, null=True)
    order = models.PositiveIntegerField(default=0, unique=True)

    class Meta:
        verbose_name_plural = 'Statuses'
        ordering = ['order']

    def __str__(self):
        return self.name


class Issue(models.Model):

    issue_type = models.ForeignKey(IssueType, on_delete=models.PROTECT)
    issue_priority = models.ForeignKey(IssuePriority, null=True, on_delete=models.PROTECT)
    issue_tags = models.ManyToManyField(IssueTag, blank=True, help_text='If desired, add multiple tags to this issue')
    issue_status = models.ForeignKey(IssueStatus, null=True, help_text='Current status of this issue')
    user_submitted_by = models.ForeignKey(User, on_delete=models.PROTECT)

    datetime_submitted = models.DateTimeField()
    description = models.TextField()
    error_screen = models.TextField(
        null=True, blank=True,
        help_text='Any error screen details. (Note the ability to click "Switch to copy-and-paste view" to copy Traceback)'
    )

qatrack/issue_tracker/forms.py
from django import forms
from django.core.exceptions import ValidationError, ImproperlyConfigured
from django.db.models import ObjectDoesNotExist, Q
from django.utils.encoding import force_text
from form_utils.forms import BetterModelForm

from qatrack.issue_tracker import models as i_models


class IssueForm(BetterModelForm):

    class Meta:
        model = i_models.Issue
        fieldsets = [
            ('hidden_fields', {
                'fields': [],
            }),
            ('required_fields', {
                'fields': [
                    'issue_type', 'issue_priority', 'issue_tags', 'description', 'error_screen'
                ],
            }),
            ('optional_fields', {
                'fields': []
            })
        ]

    def __init__(self, *args, **kwargs):
        super(IssueForm, self).__init__(*args, **kwargs)

        self.fields['issue_type'].label = 'Type'
        self.fields['issue_priority'].label = 'Priority'
        self.fields['issue_priority'].label = 'Priority'
        self.fields['error_screen'].label = 'Error Screen Details'
        # s = i_models.IssueTag.objects.get(pk=100)

        for f in self.fields:
            self.fields[f].widget.attrs['class'] = 'form-control'

        for f in ['description', 'error_screen']:
            self.fields[f].widget.attrs['class'] += ' autosize'
            self.fields[f].widget.attrs['rows'] = 8
            self.fields[f].widget.attrs['cols'] = 8

qatrack/issue_tracker/views.py
from braces.views import LoginRequiredMixin
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse, resolve
from django.forms.utils import timezone
from django.http import HttpResponseRedirect
from django.template.loader import get_template
from django.views.generic import DetailView, CreateView

from listable.views import (
    BaseListableView,
    DATE_RANGE,
    LAST_MONTH,
    LAST_WEEK,
    SELECT_MULTI,
    SELECT_MULTI_FROM_MULTI,
    TEXT,
    TODAY,
    YESTERDAY,
)

from qatrack.issue_tracker import models as i_models
from qatrack.issue_tracker import forms as i_forms


class IssueCreate(LoginRequiredMixin, CreateView):

    model = i_models.Issue
    # form_class = AuthorForm
    template_name = 'issue_tracker/issue_form.html'
    form_class = i_forms.IssueForm

    def form_valid(self, form):

        self.get_context_data()

        issue = form.save(commit=False)
        issue.user_submitted_by = self.request.user
        issue.datetime_submitted = timezone.now()
        issue.issue_status = i_models.IssueStatus.objects.get(order=0)
        issue.save()
        issue.issue_tags.set(form.cleaned_data['issue_tags'])

        return HttpResponseRedirect(reverse('issue_list'))

    def get_context_data(self, **kwargs):
        context = super(IssueCreate, self).get_context_data(**kwargs)
        colours = {}
        for c in i_models.IssuePriority.objects.all():
            colours[c.id] = c.colour
        context['colours'] = colours
        tags = {}
        for t in i_models.IssueTag.objects.all():
            tags[t.id] = [t.name, t.description]
        context['tags'] = tags
        return context


class IssueDetails(LoginRequiredMixin, DetailView):

    model = i_models.Issue
    # form_class = AuthorForm
    template_name = 'issue_tracker/issue_details.html'

    def get_context_data(self, **kwargs):
        context = super(IssueDetails, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        ct = ContentType.objects.get(app_label='issue_tracker', model='issue').id
        context['ct'] = ct

        colours = {}
        for c in i_models.IssuePriority.objects.all():
            colours[c.id] = c.colour
        context['colours'] = colours

        return context


class IssueList(BaseListableView):
    model = i_models.Issue
    template_name = 'issue_tracker/issue_list.html'
    paginate_by = 50

    order_by = ['-datetime_submitted']
    kwarg_filters = None
    multi_separator = '<span class="padding-0-10">|</span>'

    fields = (
        'actions',
        'pk',
        'issue_type__name',
        'issue_priority__name',
        'user_submitted_by__username',
        'description',
        'datetime_submitted',
        'issue_tags__name',
        'issue_status__name'
    )

    headers = {
        'actions': 'Actions',
        'pk': 'ID',
        'issue_type__name': 'Type',
        'issue_priority__name': 'Priority',
        'user_submitted_by__username': 'Submitted By',
        'description': 'Description',
        'datetime_submitted': 'Submitted',
        'issue_tags__name': 'Tags',
        'issue_status__name': 'Status'
    }

    widgets = {
        'actions': None,
        'pk': TEXT,
        'issue_type__name': SELECT_MULTI,
        'issue_priority__name': SELECT_MULTI,
        'user_submitted_by__username': SELECT_MULTI,
        'description': TEXT,
        'datetime_submitted': DATE_RANGE,
        'issue_tags__name': SELECT_MULTI_FROM_MULTI,
        'issue_status__name': SELECT_MULTI
    }

    search_fields = {
        'actions': False,
    }

    order_fields = {
        'actions': False,
        'datetime_submitted': 'datetime_submitted',
        'issue_tags__name': False
    }

    date_ranges = {
        'datetime_submitted': (TODAY, YESTERDAY, LAST_WEEK, LAST_MONTH)
    }

    select_related = (
        'issue_type',
        'issue_priority',
        'user_submitted_by',
        'issue_status'
    )

    prefetch_related = (
        'issue_tags',
    )

    def get_icon(self):
        return 'fa-bug'

    def get_page_title(self, f=None):
        if not f:
            return 'All Issues'

    def get_context_data(self, *args, **kwargs):
        context = super(IssueList, self).get_context_data(*args, **kwargs)
        current_url = resolve(self.request.path_info).url_name
        context['view_name'] = current_url
        context['icon'] = self.get_icon()
        f = self.request.GET.get('f', False)
        context['kwargs'] = {'f': f} if f else {}
        context['page_title'] = self.get_page_title(f)

        return context

    def actions(self, i):
        template = get_template('issue_tracker/table_context_issue_actions.html')
        mext = reverse('issue_list')
        c = {'i': i, 'request': self.request, 'next': mext}
        return template.render(c)

    def datetime_submitted(self, i):
        template = get_template('service_log/table_context_datetime.html')
        c = {'datetime': i.datetime_submitted}
        return template.render(c)

    def issue_priority__name(self, i):
        template = get_template('issue_tracker/table_context_issue_priority.html')
        c = {'issue_priority': i.issue_priority, 'request': self.request}
        return template.render(c)

    def issue_status__name(self, i):
        template = get_template('issue_tracker/table_context_issue_status.html')
        c = {'issue_status': i.issue_status, 'request': self.request}
        return template.render(c)

    def description(self, i):
        template = get_template('issue_tracker/table_context_issue_description.html')
        c = {'description': i.description, 'request': self.request}
        return template.render(c)

qatrack/issue_tracker/templates/issue_tracker/issue_details.html
{% extends "site_base.html" %}

{% load widget_tweaks %}
{% load qa_tags %}
{% load comments %}

{% block head_title %}Issue{% endblock %}

{% block extra_css %}
    {{ block.super }}
    <link href="{{ STATIC_URL }}daterangepicker/css/daterangepicker.css?v={{ VERSION }}" rel="stylesheet">
    <link href="{{ STATIC_URL }}qatrack_core/css/custom-daterangepicker.css?v={{ VERSION }}" rel="stylesheet">
    <link href="{{ STATIC_URL }}select2/css/select2.min.css?v={{ VERSION }}" rel="stylesheet">
    <link href="{{ STATIC_URL }}qatrack_core/css/tables.css?v={{ VERSION }}" rel="stylesheet">
    <link href="{{ STATIC_URL }}qatrack_core/css/custom-select2.css?v={{ VERSION }}" rel="stylesheet">
    <link href="{{ STATIC_URL }}issue_tracker/css/issues.css?v={{ VERSION }}" rel="stylesheet">
{% endblock extra_css %}

{% block extra_js %}
    <script type="text/javascript">

    </script>
{% endblock extra_js %}

{% block require_javascript %}
    require(['issues']);
{% endblock require_javascript %}

{% block body %}

        <div class="max-width-lg">
{#            <div class="row">#}
{#                <div class="col-md-3">#}
{#                    <h3 class="no-margin-top">Edit Issue {{ issue.id }}</h3>#}
{#                </div>#}
{#            </div>#}
{#            <div class="col-md-12">#}
{#                <dl class="pull-right">#}
{#                    <dt>Submitted:</dt>#}
{#                    <dd>#}
{#                        <div>{{ issue.datetime_submitted }}</div>#}
{#                        <div>by {{ issue.user_submitted_by }}</div>#}
{#                    </dd>#}
{#                </dl>#}
{#            </div>#}
            <div class="row">
                <div class="col-md-12">
                    <div class="box">
                        <div class="box-header">
                            <div class="row">
                                <div class="col-md-3">
                                    <h3 class="no-margin-top">Issue {{ issue.id }} Details</h3>
                                </div>
                            </div>
                        </div>
                        <div class="box-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <dl class="dl-horizontal">
                                        <dt class="margin-bottom-10">Status:</dt><dd><div class="label smooth-border" style="border-color: {{ issue.issue_status.colour }}">{{ issue.issue_status.name }}</div></dd>
                                        <dt class="margin-bottom-10">Priority:</dt><dd><span>{{ issue.issue_priority.name }}</span><span><i class="fa fa-square fa-lg margin-left-10" style="color: {{ issue.issue_priority.colour }}; margin-top: 5px;"></i></span></dd>
                                        <dt class="margin-bottom-10">Submitted:</dt><dd><div>{{ issue.datetime_submitted }}</div></dd>
                                        <dt class="margin-bottom-10">Submitted By:</dt><dd><div>{{ issue.user_submitted_by }}</div></dd>
                                        <dt class="margin-bottom-10">Type:</dt><dd><div>{{ issue.issue_type.name }}</div></dd>
                                        <dt class="margin-bottom-10">Tags:</dt><dd><div>
                                            <ul>
                                                {% for it in issue.issue_tags.all %}
                                                    <li>{{ it.name }}</li>
                                                {% endfor %}
                                            </ul>
                                        </div></dd>
                                        <dt class="margin-bottom-10">Description:</dt><dd><div class="white-space-pre">{{ issue.description }}</div></dd>
                                        <dt class="margin-bottom-10">Error Screen:</dt><dd><div class="white-space-pre">{{ issue.error_screen }}</div></dd>
                                    </dl>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <h4>Comments:</h4>
                                    {% render_comment_list for issue %}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
{#                                    {% render_comment_form for issue %}#}
                                    {% get_comment_form for issue as form %}

                                    <form action="{% comment_form_target %}" method="post">
                                        {% csrf_token %}
                                        <input id="id_name" maxlength="50" name="name" type="hidden" required="" value="{{ user.username }}">
                                        {{ form.object_pk }}
                                        {{ form.content_type }}
{#                                        {{ form.comment }}#}
                                        {{ form.security_hash }}
                                        {{ form.timestamp }}
                                        <textarea cols="40" id="id_comment" maxlength="3000" name="comment" rows="4" required="" class="margin-bottom-20 form-control autosize"></textarea>
                                        <input type="hidden" name="next" value="{% url 'issue_details' issue.id %}" />
                                        <div class="row">
                                            <div class="col-md-12">
                                                <input class="btn btn-flat btn-primary btn-sm" type="submit" name="submit" value="Post">
{#                                                <input type="submit" name="preview" value="Preview">#}
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>


        </div>

{% endblock body %}

qatrack/issue_tracker/templates/issue_tracker/issue_form.html
{% extends "site_base.html" %}

{% load widget_tweaks %}
{% load qa_tags %}
{% load comments %}

{% block head_title %}Issue{% endblock %}

{% block extra_css %}
    {{ block.super }}
    <link href="{{ STATIC_URL }}daterangepicker/css/daterangepicker.css?v={{ VERSION }}" rel="stylesheet">
    <link href="{{ STATIC_URL }}qatrack_core/css/custom-daterangepicker.css?v={{ VERSION }}" rel="stylesheet">
    <link href="{{ STATIC_URL }}select2/css/select2.min.css?v={{ VERSION }}" rel="stylesheet">
    <link href="{{ STATIC_URL }}qatrack_core/css/tables.css?v={{ VERSION }}" rel="stylesheet">
    <link href="{{ STATIC_URL }}qatrack_core/css/custom-select2.css?v={{ VERSION }}" rel="stylesheet">
    <link href="{{ STATIC_URL }}issue_tracker/css/issues.css?v={{ VERSION }}" rel="stylesheet">
{% endblock extra_css %}

{% block extra_js %}
    <script type="text/javascript">
         var colours = {{ colours|safe }};
         var tags = {{ tags|safe }};
    </script>
{% endblock extra_js %}

{% block require_javascript %}
    require(['issues']);
{% endblock require_javascript %}

{% block body %}

    <form action="" method="post" novalidate>
        {% csrf_token %}
        <div class="max-width-lg">
            <div class="row">
                <div class="col-md-3">
                    {% if form.instance.id %}
                        <h3 class="no-margin-top">Edit Issue {{ form.instance.id }}</h3>
                    {% else %}
                        <h3 class="no-margin-top">Create Issue</h3>
                    {% endif %}
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="box">
                        <div class="box-header">

                        </div>
                        <div class="box-body">
                            <div class="row" style="display: none;">

                                {% for field in form.hidden_fields %}
                                    {{ field }}
                                    {% if field.errors %}
                                        {{ field.errors }}
                                    {% endif %}
                                {% endfor %}
                            </div>
                            <div class="row">
                                <div class="col-md-12 form-horizontal">

                                    {% for field in form.fieldsets.required_fields %}
                                        <div class="form-group {% if field.errors %}has-error{% endif %}" title="{{ field.help_text }}">
                                            {% if 'autosize' in field.field.widget.attrs.class %}
                                                <div class="col-sm-12">
                                                    <label for="{{ field.id_for_label }}" class="">{{ field.label }}</label>
                                                    {{ field }}
                                                    {% for e in field.errors %}
                                                        <div class="col-sm-12 help-block text-center">{{ e }}</div>
                                                    {% endfor %}
                                                    {% if field.help_text %}
                                                        {% if field.id_for_label == 'id_error_screen' %}
                                                            <div class="col-sm-12 help-block text-center">
                                                                <a class="pic_click cursor-pointer">{{ field.help_text }}</a>
                                                                <div class="pic_display" style="display: none;">
                                                                    <img class="error-pic" src="{{ STATIC_URL }}issue_tracker/img/error-example.png?v={{ VERSION }}">
                                                                </div>
                                                            </div>
                                                        {% else %}
                                                            <div class="col-sm-12 help-block text-center">{{ field.help_text }}</div>
                                                        {% endif %}
                                                    {% endif %}
                                                </div>
                                            {% else %}
                                                <label for="{{ field.id_for_label }}" class="col-sm-4">{{ field.label }}</label>
                                                <div class="col-sm-8">
                                                    {{ field }}
                                                </div>
                                                {% for e in field.errors %}
                                                    <div class="col-sm-12 help-block text-center">{{ e }}</div>
                                                {% endfor %}
                                                {% if field.help_text %}
                                                    <div class="col-sm-12 help-block text-center">{{ field.help_text }}</div>
                                                {% endif %}
                                            {% endif %}
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 form-horizontal">

                                    {% for field in form.fieldsets.optional_fields %}
                                        <div class="form-group {% if field.errors %}has-error{% endif %}" title="{{ field.help_text }}">
                                            {% if 'autosize' in field.field.widget.attrs.class %}
                                                <div class="col-sm-12">
                                                    <label for="{{ field.id_for_label }}" class="">{{ field.label }}</label>
                                                    {{ field }}
                                                    {% for e in field.errors %}
                                                        <div class="col-sm-12 help-block text-center">{{ e }}</div>
                                                    {% endfor %}
                                                </div>
                                            {% else %}
                                                <label for="{{ field.id_for_label }}" class="col-sm-4">{{ field.label }}</label>
                                                <div class="col-sm-8">
                                                    {{ field }}
                                                </div>
                                                {% for e in field.errors %}
                                                    <div class="col-sm-12 help-block text-center">{{ e }}</div>
                                                {% endfor %}
                                            {% endif %}
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>

{#                            <div class="row">#}
{#                                <div class="col-md-12">#}
{#                                    <h4>Comments</h4>#}
{#                                    {% render_comment_form for form.instance %}#}
{#                                    {% get_comment_form for event as form %}#}
{#                                    <table>#}
{#                                      <form action="{% comment_form_target %}" method="post">#}
{#                                        {% csrf_token %}#}
{#                                        {{ form }}#}
{#                                        <tr>#}
{#                                          <td colspan="2">#}
{#                                            <input type="submit" name="submit" value="Post">#}
{#                                            <input type="submit" name="preview" value="Preview">#}
{#                                          </td>#}
{#                                        </tr>#}
{#                                      </form>#}
{#                                    </table>#}
{#                                </div>#}
{#                            </div>#}
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <input class="btn btn-flat btn-primary" type="submit" value="Add Issue" />
                </div>
            </div>

        </div>

    </form>
{% endblock body %}

qatrack/issue_tracker/templates/issue_tracker/issue_list.html
{% extends "site_base.html" %}

{% load qa_tags %}
{% load listable %}

{% block head_title %}{{page_title}}{% endblock %}

{% block extra_css %}
    {{ block.super }}
    <link href="{{ STATIC_URL }}datepicker/css/bootstrap-datepicker.min.css?v={{VERSION}}" rel="stylesheet">
    <link href="{{ STATIC_URL }}multiselect/css/bootstrap.multiselect.css?v={{VERSION}}" rel="stylesheet">
    <link href="{{ STATIC_URL }}daterangepicker/css/daterangepicker.css?v={{VERSION}}" rel="stylesheet">
    <link href="{{ STATIC_URL }}qatrack_core/css/tables.css?v={{VERSION}}" rel="stylesheet">
    <link href="{{ STATIC_URL }}qatrack_core/css/custom-daterangepicker.css?v={{VERSION}}" rel="stylesheet">
    <link href="{{ STATIC_URL }}issue_tracker/css/issues.css?v={{ VERSION }}" rel="stylesheet">
{% endblock extra_css %}

{% block extra_js %}
    {% autoescape off %}
        {% listable view_name dom="<'row'<'col-sm-5'i><'col-sm-7'p>><'row'<'col-sm-12'tr>><'row'<'col-sm-5'><'col-sm-7'p>>" requirejs=True pagination_type='bootstrap3' css_table_class='table-hover table-condensed table-striped' css_input_class='btn-flat btn-sm input-sm full-width' auto_width=False %}
    {% endautoescape %}
{% endblock %}

{% block require_javascript %}
    require(['listable']);
{% endblock require_javascript %}

{% block body %}

    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header">
                    <i class="fa {{ icon }} fa-fw" aria-hidden="true"></i>
                    <h3 class="box-title">{{page_title}}</h3>

                </div>
                <div class="box-body pad">
                    {{ listable_table }}
                </div>
            </div>
        </div>
    </div>

{% endblock body %}

qatrack/issue_tracker/templates/issue_tracker/table_context_issue_actions.html
{% load qa_tags %}
<div style="min-width: 85px;">
    <a class="btn btn-primary btn-xs btn-flat" href="{% url 'issue_details' i.pk %}{% if next %}?next={{ next }}{% endif %}">View</a>
</div>

qatrack/issue_tracker/templates/issue_tracker/table_context_issue_description.html
{% load qa_tags %}

<div class="hide-extra-text" title="{{ description }}" data-title="Problem Description">{{ description|truncatechars:100 }}</div>

qatrack/issue_tracker/templates/issue_tracker/table_context_issue_priority.html
{% load qa_tags %}
<span style="min-width: 150px;">
{#    <div class="border-bottom-3" style="border-color: {{ issue_priority.colour }}">{{ issue_priority.name }}</div>#}
    {{ issue_priority.name }}
    <i class="fa fa-square fa-lg pull-left" style="color: {{ issue_priority.colour }}; margin-top: 5px;"></i>
    {#<div class="label pull-right" style="background-color: {{ service_status.colour }}">&nbsp;</div>#}
</span>

qatrack/issue_tracker/templates/issue_tracker/table_context_issue_status.html
{% load qa_tags %}
<span style="min-width: 150px;">
    <div class="label smooth-border" style="border-color: {{ issue_status.colour }}">{{ issue_status.name }}</div>
    {#<div class="label pull-right" style="background-color: {{ service_status.colour }}">&nbsp;</div>#}
</span>