qatrack/api/service_log/urls.py
from django.conf.urls import include, url
from rest_framework import routers

from qatrack.api.service_log import views

router = routers.DefaultRouter()
router.register(r'serviceareas', views.ServiceAreaViewSet)
router.register(r'unitserviceareas', views.UnitServiceAreaViewSet)
router.register(r'servicetypes', views.ServiceTypeViewSet)
router.register(r'serviceeventstatus', views.ServiceEventStatusViewSet)
router.register(r'serviceevents', views.ServiceEventViewSet)
router.register(r'thirdparty', views.ThirdPartyViewSet)
router.register(r'hours', views.HoursViewSet)
router.register(r'returntoserviceqa', views.ReturnToServiceQAViewSet)
router.register(r'grouplinker', views.GroupLinkerViewSet)
router.register(r'grouplinkerinstance', views.GroupLinkerInstanceViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
]

qatrack/service_log/urls.py
from django.conf.urls import url

from qatrack.service_log import views

urlpatterns = [
    url(r"^$", views.SLDashboard.as_view(), name="sl_dash"),
    url(r'^event/$', views.ServiceEventsBaseList.as_view(), name="sl_list_all"),
    url(r'^event/create/$', views.CreateServiceEvent.as_view(), name='sl_new'),
    url(r'^event/create/choose-unit/$', views.ChooseUnitForNewSE.as_view(), name="sl_unit_new"),
    url(r'^event/edit(?:/(?P<pk>\d+))?/$', views.UpdateServiceEvent.as_view(), name="sl_edit"),
    url(r'^event/details(?:/(?P<pk>\d+))?/$', views.DetailsServiceEvent.as_view(), name="sl_details"),
    url(r'^event/delete(?:/(?P<pk>\d+))?/$', views.DeleteServiceEvent.as_view(), name='se_delete'),
    url(r'^event/review-required/$', views.ServiceEventsReviewRequiredList.as_view(), name="sl_list_review_required"),
    url(r'^event/review/choose-unit/$', views.ChooseUnitForViewSE.as_view(), name="sl_unit_view_se"),
    url(r'^event/unit/(?P<unit_number>\d+)/$', views.ServiceEventsByUnitList.as_view(), name="sl_list_by_unit"),
    url(r'^event/initiated-by/(?P<tli_pk>\d+)/$', views.ServiceEventsInitiatedByList.as_view(), name="sl_list_initiated_by"),
    url(r'^event/return-to-service-for/(?P<tli_pk>\d+)/$', views.ServiceEventsReturnToServiceForList.as_view(), name="sl_list_return_to_service_for"),
    url(r'^event/status/(?P<pk>\d+)/$', views.ServiceEventsByStatusList.as_view(), name="sl_list_by_status"),
    url(r'^rtsqa/$', views.ReturnToServiceQABaseList.as_view(), name="rtsqa_list_all"),
    url(r'^rtsqa/incomplete/$', views.ReturnToServiceQAIncompleteList.as_view(), name="rtsqa_list_incomplete"),
    url(r'^rtsqa/unreviewed/$', views.ReturnToServiceQAUnreviewedList.as_view(), name="rtsqa_list_unreviewed"),
    url(r'^rtsqa/event/(?P<se_pk>\d+)$', views.ReturnToServiceQAForEventList.as_view(), name="rtsqa_list_for_event"),
    url(r'^se-searcher/$', views.se_searcher, name="se_searcher"),
    url(r'^tli-select(?:/(?P<pk>\d+))?(?:/(?P<form>[a-zA-Z0-9-_]+)/)?$', views.TLISelect.as_view(), name="tli_select"),
    url(r'^tli-statuses/$', views.tli_statuses, name="tli_statuses"),
    url(r'^unit-sa_utc/$', views.unit_sa_utc, name="unit_sa_utc"),
    url(r'^err/$', views.ErrorView.as_view(), name='err'),
    url(r'^down-time/$', views.ServiceEventDownTimesList.as_view(), name='se_down_time'),
    url(r'^handle-unit-down-time/$', views.handle_unit_down_time, name='handle_unit_down_time'),
    url(r"^event/perform(?:/(?P<pk>\d+))?/$", views.PerformPM.as_view(), name="perform_pm"),
    url(r'^event/choose-pm-unit/$', views.ChooseUnitPM.as_view(), name="pm_unit_new"),
    url(r"^unit/(?P<unit_number>[/\d]+)/$", views.UnitListPM.as_view(), name="pm_by_unit"),

]

qatrack/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.templatetags.staticfiles import static as static_url
from django.views.generic.base import RedirectView, TemplateView


admin.autodiscover()


favicon_view = RedirectView.as_view(url=static_url("qatrack_core/img/favicon.ico"), permanent=True)
touch_view = RedirectView.as_view(url=static_url("qatrack_core/img/apple-touch-icon.png"), permanent=True)


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="homepage.html"), name="home"),
    url(r'^accounts/', include('qatrack.accounts.urls')),
    url(r'^qa/', include('qatrack.qa.urls')),
    url(r'^units/', include('qatrack.units.urls')),
    url(r'^core/', include('qatrack.qatrack_core.urls')),
    url(r'^dashboard/',include('qatrack.dashboard.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^favicon\.ico$', favicon_view),
    url(r'^apple-touch-icon\.png$', touch_view),

    # third party
    url(r'^', include('genericdropdown.urls')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^admin/dynamic_raw_id/', include('dynamic_raw_id.urls')),
    url(r'^api/', include('qatrack.api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.USE_SERVICE_LOG:
    urlpatterns += [url(r'^servicelog/', include('qatrack.service_log.urls'))]

if settings.USE_PARTS:
    urlpatterns += [url(r'^parts/', include('qatrack.parts.urls'))]

if settings.USE_ISSUES:
    urlpatterns += [url(r'^issues/', include('qatrack.issue_tracker.urls'))]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

qatrack/service_log/models.py
import json
import re

from datetime import timedelta, datetime

from django.conf import settings
from django.contrib.auth.models import Group, User
from django.core import urlresolvers
from django.core.serializers.json import DjangoJSONEncoder
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import Q
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.db.utils import IntegrityError
from django.utils import timezone
from django.utils.translation import ugettext as _
from django_comments.models import Comment
from django.contrib.contenttypes.fields import(
    GenericForeignKey,
    GenericRelation,
)
from django.contrib.contenttypes.models import ContentType
from qatrack.qa.models import Category, Frequency, FrequencyManager, UnitTestCollection, TestListInstance
from qatrack.units.models import NameNaturalKeyManager, Unit, Vendor
from qatrack.qa.testpack import TestPackMixin

re_255 = '([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])'
color_re = re.compile('^rgba\(' + re_255 + ',' + re_255 + ',' + re_255 + ',(0(\.[0-9][0-9]?)?|1)\)$')
validate_color = RegexValidator(color_re, _('Enter a valid color.'), 'invalid')

TOLERANCE = "tolerance"
NO_TOL = "no_tol"
ACTION = "action"
OK = "ok"

NEW_SERVICE_EVENT = 'new_se'
MODIFIED_SERVICE_EVENT = 'mod_se'
STATUS_SERVICE_EVENT = 'stat_se'
CHANGED_RTSQA = 'rtsqa'
PERFORMED_RTS = 'perf_rts'
APPROVED_RTS = 'app_rts'
DELETED_SERVICE_EVENT = 'del_se'
NO_DUE_DATE = NO_TOL
NOT_DUE = OK
DUE = TOLERANCE
OVERDUE = ACTION

LOG_TYPES = (
    (NEW_SERVICE_EVENT, 'New Service Event'),
    (MODIFIED_SERVICE_EVENT, 'Modified Servicew Event'),
    (STATUS_SERVICE_EVENT, 'Service Event Status Changed'),
    (CHANGED_RTSQA, 'Changed Return To Service'),
    (PERFORMED_RTS, 'Performed Return To Service'),
    (APPROVED_RTS, 'Approved Return To Service'),
    (DELETED_SERVICE_EVENT, 'Deleted Service Event')
)


class ServiceArea(models.Model):

    name = models.CharField(max_length=32, unique=True, help_text=_('Enter a short name for this service area'))
    units = models.ManyToManyField(Unit, through='UnitServiceArea', related_name='service_areas')

    objects = NameNaturalKeyManager()

    def natural_key(self):
        return (self.name,)

    def __str__(self):
        return self.name


class UnitServiceArea(models.Model):

    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    service_area = models.ForeignKey(ServiceArea, on_delete=models.CASCADE)

    notes = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name_plural = _('Unit Service Area Memberships')
        unique_together = ('unit', 'service_area',)
        ordering = ('unit', 'service_area')

    def __str__(self):
        return '%s :: %s' % (self.unit.name, self.service_area.name)


class ServiceType(models.Model):

    name = models.CharField(max_length=32, unique=True, help_text=_('Enter a short name for this service type'))
    is_review_required = models.BooleanField(default=True, help_text=_('Does this service type require review'))
    is_active = models.BooleanField(default=True, help_text=_('Set to false if service type is no longer used'))
    description = models.TextField(
        max_length=512, help_text=_('Give a brief description of this service type'), null=True, blank=True
    )

    objects = NameNaturalKeyManager()

    def natural_key(self):
        return (self.name,)

    def __str__(self):
        return self.name


class ServiceEventStatus(models.Model):

    name = models.CharField(max_length=32, unique=True, help_text=_('Enter a short name for this service status'))
    is_default = models.BooleanField(
        default=False,
        help_text=_(
            'Is this the default status for all service events? If set to true every other service event '
            'status will be set to false'
        )
    )
    is_review_required = models.BooleanField(
        default=True, help_text=_('Do service events with this status require review?')
    )
    rts_qa_must_be_reviewed = models.BooleanField(
        default=True,
        verbose_name=_("Return To Service (RTS) QA Must be Reviewed"),
        help_text=_(
            'Service events with Return To Service (RTS) QA that has not been reviewed '
            'can not have this status selected if set to true.'
        ),
    )
    description = models.TextField(
        max_length=512, help_text=_('Give a brief description of this service event status'), null=True, blank=True
    )
    colour = models.CharField(default=settings.DEFAULT_COLOURS[0], max_length=22, validators=[validate_color])

    objects = NameNaturalKeyManager()

    class Meta:
        verbose_name_plural = _('Service event statuses')

    def save(self, *args, **kwargs):
        if self.is_default:
            try:
                temp = ServiceEventStatus.objects.get(is_default=True)
                if self != temp:
                    temp.is_default = False
                    temp.save()
            except ServiceEventStatus.DoesNotExist:
                pass
        super(ServiceEventStatus, self).save(*args, **kwargs)

    def natural_key(self):
        return (self.name,)

    def __str__(self):
        return self.name

    @staticmethod
    def get_default():
        try:
            default = ServiceEventStatus.objects.get(is_default=True)
        except ServiceEventStatus.DoesNotExist:
            return None
        return default

    @staticmethod
    def get_colour_dict():
        return {ses.id: ses.colour for ses in ServiceEventStatus.objects.all()}


class ServiceEventManager(models.Manager):

    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(is_active=True)

    def get_deleted(self):
        return super().get_queryset().filter(is_active=False)


class ServiceEvent(models.Model):

    unit_service_area = models.ForeignKey(UnitServiceArea, on_delete=models.PROTECT)
    service_type = models.ForeignKey(ServiceType, on_delete=models.PROTECT)
    service_event_related = models.ManyToManyField(
        'self', symmetrical=True, blank=True, verbose_name=_('Related service events'),
        help_text=_('Enter the service event IDs of any related service events.')
    )
    service_status = models.ForeignKey(ServiceEventStatus, verbose_name=_('Status'), on_delete=models.PROTECT)

    user_status_changed_by = models.ForeignKey(User, null=True, blank=True, related_name='+', on_delete=models.PROTECT)
    user_created_by = models.ForeignKey(User, related_name='+', on_delete=models.PROTECT)
    user_modified_by = models.ForeignKey(User, null=True, blank=True, related_name='+', on_delete=models.PROTECT)
    test_list_instance_initiated_by = models.ForeignKey(
        TestListInstance,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='serviceevents_initiated'
    )

    datetime_status_changed = models.DateTimeField(null=True, blank=True)
    datetime_created = models.DateTimeField()
    datetime_service = models.DateTimeField(
        verbose_name=_('Date and time'), help_text=_('Date and time service performed')
    )
    datetime_modified = models.DateTimeField(null=True, blank=True)

    safety_precautions = models.TextField(
        null=True, blank=True, help_text=_('Describe any safety precautions taken')
    )
    problem_description = models.TextField(help_text=_('Describe the problem leading to this service event'))
    work_description = models.TextField(
        null=True, blank=True, help_text=_('Describe the work done during this service event')
    )
    duration_service_time = models.DurationField(
        verbose_name=_('Service time'), null=True, blank=True,
        help_text=_('Enter the total time duration of this service event (Hours : minutes)')
    )
    duration_lost_time = models.DurationField(
        verbose_name=_('Lost time'), null=True, blank=True,
        help_text=_('Enter the total clinical time lost for this service event (Hours : minutes)')
    )
    is_review_required = models.BooleanField(
        default=True, blank=True
    )
    is_active = models.BooleanField(default=True, blank=True)

    objects = ServiceEventManager()

    class Meta:
        get_latest_by = "datetime_service"

        permissions = (
            ('review_serviceevent', 'Can review service event'),
            ('view_serviceevent', 'Can view service event'),
        )

        ordering = ["-datetime_service"]

    def __str__(self):
        return str(self.id)

    def create_rts_log_details(self):
        rts_states = []
        for r in self.returntoserviceqa_set.all():

            utc = r.unit_test_collection
            if not r.test_list_instance:
                state = 'tli_incomplete'
                details = utc.name
            elif not r.test_list_instance.all_reviewed:
                state = 'tli_req_review'
                details = r.test_list_instance.test_list.name
            else:
                state = 'tli_reviewed'
                details = r.test_list_instance.test_list.name

            rts_states.append({'state': state, 'details': details})
        return rts_states

    def set_inactive(self):
        self.is_active = False
        self.save()

        parts_used = self.partused_set.all()
        for pu in parts_used:
            pu.add_back_to_storage()

    def set_active(self):
        self.is_active = True
        self.save()

        parts_used = self.partused_set.all()
        for pu in parts_used:
            pu.remove_from_storage()


class ThirdPartyManager(models.Manager):

    def get_queryset(self):
        return super(ThirdPartyManager, self).get_queryset().select_related('vendor')


class ThirdParty(models.Model):

    vendor = models.ForeignKey(Vendor, on_delete=models.PROTECT)

qatrack/service_log/templates/service_log/history.html
{% load pm_tags %}
{% if history %}
  {% for hist in history %}
    <a target="_blank"
      href="{{ hist.task_instance.get_absolute_url }}"
      title="{ {{hist.created_by}} on {{hist.work_completed}} }">
    </a>
  {% endfor %}

qatrack/service_log/templates/service_log/log_rtsqa.html
<li class="rtsqa_log" style="display: list-item;">

{#    <i class="fa fa-stack">#}
        <i class="fa fa-pencil-square-o fa-lg"></i>
{#        <i class="fa fa-pencil fa-stack-custom-sub fa-flip-horizontal upper-left primary"></i>#}
{#    </i>#}

    <div class="timeline-item{% if can_view %} can-view{% elif not instance.service_event.is_active %} deleted{% endif %}">
        <span class="time"><i class="fa fa-clock-o"></i>&nbsp;{{ datetime_display }}</span>
        <h3 class="timeline-header header-se_new"{% if can_view %} onclick="window.location='{% url 'sl_details' pk=instance.service_event.id %}'"{% endif %}>
            <div class="pull-right margin-right-20 label label-default">
                {{ instance.service_event.unit_service_area.unit.name }}
            </div>
            <div class="margin-bottom-10">{{ user }} changed return to service required for service event {{ instance.service_event_id }}{% if not instance.service_event.is_active %}<i> (deleted)</i>{% endif %}</div>
            <div>
                <div class="padding-left-10">
                    {% if extra_info|length > 0 %}
                        <div class="dash-change title row">
                            <div class="col-xs-4">Test List Name</div>
                            <div class="col-xs-4">Session Details</div>
                        </div>
                        {% for changed in extra_info %}
                            <div class="dash-change item rtsqa-row row{% if extra_info|length > 1 %} hover{% endif %} {{ changed.state }}">
                                <div class="col-sm-4 tli-name">{{ changed.details }}</div>
                                {% if changed.state == 'tli_req_review' %}
                                    <div class="col-sm-4">
                                        <div class="complete">Performed</div>
                                        <div class="incomplete">-----</div>
                                    </div>
                                {% elif changed.state == 'tli_incomplete' %}
                                    <div class="col-sm-4">
                                        <div class="incomplete">-----</div>
                                        <div class="incomplete">-----</div>
                                    </div>
                                {% elif changed.state == 'tli_reviewed' %}
                                    <div class="col-sm-4">
                                        <div class="complete">Performed</div>
                                        <div class="complete">Reviewed</div>
                                    </div>
                                {% elif changed.state == 'deleted' %}
                                    <div class="col-sm-4"><div class="del">Deleted</div></div>
                                {% endif %}
                            </div>
                        {% endfor %}
                    {% else %}
                        <div class="dash-change title row">
                            <div class="col-xs-4">All Deleted</div>
                        </div>
                    {% endif %}
                </div>
            </div>
        </h3>
    </div>
</li>

qatrack/service_log/templates/service_log/log_service_event_deleted.html
<li class="se_log" style="display: list-item;">

    <i class="fa fa-stack">
        <i class="fa fa-wrench fa-stack-custom-main fa-lg"></i>
        <i class="fa fa-times fa-stack-custom-sub upper-left danger"></i>
    </i>

    <div class="timeline-item deleted">
        <span class="time"><i class="fa fa-clock-o"></i>&nbsp;{{ datetime_display }}</span>
        <h3 class="timeline-header header-se_del">
            <div class="pull-right margin-right-20 label label-default">
                {{ instance.service_event.unit_service_area.unit.name }}
            </div>
            <div class="margin-bottom-10">{{ user }} deleted service event {{ instance.service_event_id }}</div>
            <div class="padding-left-10">


                <div class="dash-change title row">
                    <div class="col-xs-3">Reason</div>
                    <div class="col-xs-9">Comment</div>
                </div>

                <div class="dash-change item row">
                    <div class="col-xs-3">{{ extra_info.reason }}</div>
                    <div class="col-xs-9">{{ extra_info.comment }}</div>
                </div>
            </div>
        </h3>
    </div>
</li>

qatrack/service_log/templates/service_log/log_service_event_modified.html
<li class="se_log" style="display: list-item;">

    <i class="fa fa-stack">
        <i class="fa fa-wrench fa-stack-custom-main fa-lg"></i>
        <i class="fa fa-pencil fa-stack-custom-sub fa-flip-horizontal upper-left primary"></i>
    </i>

    <div class="timeline-item{% if can_view %} can-view{% elif not instance.service_event.is_active %} deleted{% endif %}">
        <span class="time"><i class="fa fa-clock-o"></i>&nbsp;{{ datetime_display }}</span>
        <h3 class="timeline-header header-se_new"{% if can_view %} onclick="window.location='{% url 'sl_details' pk=instance.service_event.id %}'"{% endif %}>
            <div class="pull-right margin-right-20 label label-default">
                {{ instance.service_event.unit_service_area.unit.name }}
            </div>
            <div class="margin-bottom-10">{{ user }} modified service event {{ instance.service_event_id }}</div>
            <div class="padding-left-10">
                {% if extra_info.items|length > 0 %}
                    <div class="dash-change title row">
                        <div class="col-xs-2">Field Changed</div>
                        <div class="col-xs-4">Old Value</div>
                        <div class="col-xs-4">New Value</div>
                    </div>
                    {% for key, val in extra_info.items %}
                        <div class="dash-change item row{% if extra_info.items|length > 1 %} hover{% endif %} ">
                            <div class="col-xs-2">{{ key }}</div>
                            <div class="col-xs-4">{{ val.old }}</div>
                            <div class="col-xs-4">{{ val.new }}</div>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </h3>
    </div>
</li>

qatrack/service_log/templates/service_log/service_event_delete.html
{% extends "service_log/sl_base.html" %}

{% load widget_tweaks %}
{% load qa_tags %}
{% load qatrack_tags %}
{% load comments %}

{% block head_title %}Service Event{% endblock %}

{% block extra_css %}
    {{ block.super }}
    <link href="{{ STATIC_URL }}select2/css/select2.min.css?v={{ VERSION }}" rel="stylesheet">
    <link href="{{ STATIC_URL }}qatrack_core/css/tables.css?v={{ VERSION }}" rel="stylesheet">
    <link href="{{ STATIC_URL }}qatrack_core/css/custom-select2.css?v={{ VERSION }}" rel="stylesheet">
{% endblock extra_css %}

{% block extra_js %}
{% endblock extra_js %}

{% block require_javascript %}
    require(['sl_se_delete']);
{% endblock require_javascript %}

{% block body %}

    <form id="service-event-delete-form" action="" method="post" novalidate>
        {% csrf_token %}
        <div class="max-width-lg">
            <div class="row margin-bottom-15">
                <div class="col-md-3">
                    <h4 class="no-margin-top">Delete Service Event {{ serviceevent.id }}</h4>
                    {% service_status_label serviceevent.service_status size="14" %}
                </div>
            </div>

            <div class="row">
                <div class="col-sm-12">
                    <div class="box box-default">

{#                        <div class="box-header">#}
{#                            <h4 class="box-title">Deleting will effect the following related items</h4>#}
{#                        </div>#}

                        <div class="box-body">




                            <div class="row margin-bottom-15">
                                <div class="col-sm-4">
                                    <div class="form-group {% if form.reason.errors %}has-error{% endif %}" title="{{ form.reason.help_text }}">
                                        <div class="col-sm-12">
                                            <label for="{{ form.reason.id_for_label }}" class="">
                                                <span>{{ form.reason.label }}{% if form.reason.field.required %} *{% endif %}</span>
                                                {% if form.reason.help_text %} - <span class="help-block margin-bottom-0 display-inline-block">{{ form.reason.help_text }}</span>{% endif %}
                                            </label>
                                            {{ form.reason }}
                                            {% for e in form.reason.errors %}
                                                <div class="col-sm-12 help-block text-center">{{ e }}</div>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>

                                <div class="col-sm-8">
                                    <div class="form-group {% if form.comment.errors %}has-error{% endif %}" title="{{ form.comment.help_text }}">
                                        <div class="col-sm-12">
                                            <label for="{{ form.comment.id_for_label }}" class="">
                                                <span>{{ form.comment.label }}{% if form.comment.field.required %} *{% endif %}</span>
                                                {% if form.comment.help_text %} - <span class="help-block margin-bottom-0 display-inline-block">{{ form.comment.help_text }}</span>{% endif %}
                                            </label>
                                            {{ form.comment }}
                                            {% for e in form.comment.errors %}
                                                <div class="col-sm-12 help-block text-center">{{ e }}</div>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>

                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    {% if perms.service_log.delete_service_event %}
                                        <div id="submit-delete" class="btn btn-flat btn-danger service-save pull-right">Delete</div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </form>


{% endblock body %}

qatrack/service_log/templates/service_log/service_event_status_label.html
<span class="label smooth-border" style="border-color: {{ colour }}; font-size: {{ size }}px;">{{ name }}</span>

qatrack/service_log/templates/service_log/table_context_datetime.html
<div>{{ datetime }}</div>

qatrack/service_log/templates/service_log/table_context_se_actions.html
{% load qa_tags %}
<div style="min-width: 85px;">
    {% if perms.service_log.change_serviceevent %}
        <a class="btn btn-default btn-xs btn-flat"
          href="{% url 'sl_edit' se.pk %}{% if next %}?next={{ next }}{% endif %}"
          title="Click to edit this Service Event"
          >
          Edit
      </a>
    {% endif %}
    {% if perms.service_log.view_serviceevent %}
        <a class="btn btn-default btn-xs btn-flat"
           href="{% url 'sl_details' se.pk %}"
           title="Click to view details of this Service Event"
          >Details</a>
    {% endif %}
</div>

qatrack/service_log/templates/service_log/table_context_service_status.html
{% load qa_tags %}
<span style="min-width: 150px;">
    {{ service_status.name }}
    <i class="fa fa-square fa-lg pull-right" style="color: {{ service_status.colour }}"></i>
    {#<div class="label pull-right" style="background-color: {{ service_status.colour }}">&nbsp;</div>#}
</span>

qatrack/service_log/templates/service_log/table_context_tli_work_completed.html
{% if in_progress %}
    <abbr title="Started {{ datetime_started }} by {{ created_by }}"><em>In Progress</em></abbr>
{% else %}
    <div>{{ datetime_completed }}</div>
{% endif %}

qatrack/service_log/templates/service_log/taskinstance_work_completed.html
{% load pm_tags %}
{% if instance %}
    {% if instance.in_progress %}
        <span data-timestamp="{{instance.work_started|date:"U"}}">
            <abbr title="Started by {{instance.modified_by}}">{{instance.work_started}}</abbr>
        </span>
    {% else %}
        <span data-timestamp="{{instance.work_completed|date:"U"}}">
            <abbr title="Completed by {{instance.created_by}}, Last modified by {{instance.modified_by}}">{{instance.work_completed}}</abbr>
        </span>
    {% endif %}
{% else %}
    <em>New List</em>
{% endif %}

qatrack/service_log/templates/service_log/unittask_actions.html
{% load pm_tags %}
<a class="btn btn-default btn-xs btn-flat"
  href="{% url 'perform_pm' ut.pk %}?day=next&next={{request.path|cut:"data/"}}"
  title="Perform {{ ut.name }} for Unit {{ ut.unit.name }}">
  Perform
</a>