qatrack/api/units/urls.py
from django.conf.urls import include, url
from rest_framework import routers

from qatrack.api.units import views

router = routers.DefaultRouter()
router.register(r'units', views.UnitViewSet)
router.register(r'vendors', views.VendorViewSet)
router.register(r'unitclasses', views.UnitClassViewSet)
router.register(r'unittypes', views.UnitTypeViewSet)
router.register(r'modalities', views.ModalityViewSet)
router.register(r'sites', views.SiteViewSet)
router.register(r'availabletimes', views.UnitAvailableTimeViewSet)
router.register(r'availabletimeedits', views.UnitAvailableTimeEditViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
]

qatrack/units/urls.py
from django.conf.urls import include, url

from qatrack.units import views

urlpatterns = [
    url(r"^unit_available_time(?:/(?P<pk>\d+))?/$", views.UnitAvailableTimeChange.as_view(), name="unit_available_time"),
    url(r'^handle_unit_available_time/$', views.handle_unit_available_time, name='handle_unit_available_time'),
    url(r'^handle_unit_available_time_edit/$', views.handle_unit_available_time_edit, name='handle_unit_available_time_edit'),
    url(r'^delete_schedules/$', views.delete_schedules, name='delete_schedules'),
    url(r'^get_unit_available_time_data/$', views.get_unit_available_time_data, name='get_unit_available_time_data'),
]

qatrack/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.templatetags.staticfiles import static as static_url
from django.views.generic.base import RedirectView, TemplateView


admin.autodiscover()


favicon_view = RedirectView.as_view(url=static_url("qatrack_core/img/favicon.ico"), permanent=True)
touch_view = RedirectView.as_view(url=static_url("qatrack_core/img/apple-touch-icon.png"), permanent=True)


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="homepage.html"), name="home"),
    url(r'^accounts/', include('qatrack.accounts.urls')),
    url(r'^qa/', include('qatrack.qa.urls')),
    url(r'^units/', include('qatrack.units.urls')),
    url(r'^core/', include('qatrack.qatrack_core.urls')),
    url(r'^dashboard/',include('qatrack.dashboard.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^favicon\.ico$', favicon_view),
    url(r'^apple-touch-icon\.png$', touch_view),

    # third party
    url(r'^', include('genericdropdown.urls')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^admin/dynamic_raw_id/', include('dynamic_raw_id.urls')),
    url(r'^api/', include('qatrack.api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.USE_SERVICE_LOG:
    urlpatterns += [url(r'^servicelog/', include('qatrack.service_log.urls'))]

if settings.USE_PARTS:
    urlpatterns += [url(r'^parts/', include('qatrack.parts.urls'))]

if settings.USE_ISSUES:
    urlpatterns += [url(r'^issues/', include('qatrack.issue_tracker.urls'))]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

qatrack/units/models.py
import calendar

from django.conf import settings
from django.db import models
from django.utils.timezone import timedelta
from django.utils.translation import ugettext as _

# from qatrack.qa.models import Frequency


# ServiceArea = apps.get_app_config('service_log').get_model('ServiceArea')
# UnitServiceArea = apps.get_app_config('service_log').get_model('UnitServiceArea')

PHOTON = 'photon'
ELECTRON = 'electron'


class NameNaturalKeyManager(models.Manager):

    def get_by_natural_key(self, name):
        return self.get(name=name)


class Vendor(models.Model):
    """ Vendor of Unit

    Stores information (just name for now) of unit vendor.
    """

    name = models.CharField(max_length=64, unique=True, help_text=_('Name of this vendor'))
    notes = models.TextField(max_length=255, blank=True, null=True, help_text=_('Additional notes about this vendor'))

    objects = NameNaturalKeyManager()

    class Meta:
        ordering = ("name",)

    def natural_key(self):
        return (self.name,)

    def __str__(self):
        """Display more descriptive name"""
        return self.name


class UnitClass(models.Model):
    """ Class of unit

    Unit class, ie. linac, CT, MR, etc.
    """

    name = models.CharField(max_length=64, unique=True, help_text=_('Name of this unit class'))

    objects = NameNaturalKeyManager()

    class Meta:
        verbose_name_plural = "Unit classes"
        ordering = ("name",)

    def natural_key(self):
        return (self.name,)

    def __str__(self):
        """Display more descriptive name"""
        return self.name


class Site(models.Model):
    """ Site unit resides

    Allows for multiple site filtering (different campuses, buildings, hospitals, etc)
    """
    name = models.CharField(max_length=64, unique=True, help_text=_('Name of this site'))

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name


class UnitTypeManager(models.Manager):

    def get_by_natural_key(self, name, model, vendor_name, unitclass_name):
        return self.get(name=name, model=model, vendor__name=vendor_name, unit_class__name=unitclass_name)


class UnitType(models.Model):
    """Radiation Device Type

    Stores a device type for grouping individual :model:`unit`s together.
    For example, your Elekta Linacs might form one group, and your Tomo's
    another.

    """
    vendor = models.ForeignKey(Vendor, null=True, blank=True, on_delete=models.PROTECT)
    unit_class = models.ForeignKey(UnitClass, null=True, blank=True, on_delete=models.PROTECT)

    name = models.CharField(max_length=50, help_text=_('Name for this unit type'))
    model = models.CharField(max_length=50, null=True, blank=True, help_text=_('Optional model name for this group'))

    objects = UnitTypeManager()

    class Meta:
        unique_together = [('name', 'model', 'vendor', 'unit_class',)]
        ordering = ("vendor__name", "name",)

    def natural_key(self):
        return (self.name, self.model) + self.vendor.natural_key() + self.unit_class.natural_key()
    natural_key.dependencies = ["units.vendor", "units.unitclass"]

    def __str__(self):
        """Display more descriptive name"""
        return '%s%s' % (self.name, ' - %s' % self.model if self.model else '')


class Modality(models.Model):
    """Treatment modalities

    defines available treatment modalities for a given :model:`unit1`

    """

    name = models.CharField(
        _('Name'),
        max_length=255,
        help_text=_('Descriptive name for this modality'),
        unique=True
    )

    objects = NameNaturalKeyManager()

    class Meta:
        verbose_name_plural = _('Modalities')

    def natural_key(self):
        return (self.name,)

    def __str__(self):
        return self.name


def weekday_count(start_date, end_date, uate_list):
    week = {}
    for i in range((end_date - start_date).days + 1):
        day = start_date + timedelta(days=i)
        if str(day) not in uate_list:
            day_name = calendar.day_name[day.weekday()].lower()
            week[day_name] = week[day_name] + 1 if day_name in week else 1
    return week


class Unit(models.Model):
    """Radiation devices
    Stores a single radiation device (e.g. Linac, Tomo unit, Cyberkinfe etc.)
    """
    type = models.ForeignKey(UnitType, verbose_name=_("Unit Type"), on_delete=models.PROTECT)
    site = models.ForeignKey(Site, null=True, blank=True, on_delete=models.PROTECT)

    number = models.PositiveIntegerField(null=False, unique=True, help_text=_('A unique number for this unit'))
    name = models.CharField(max_length=256, help_text=_('The display name for this unit'))
    serial_number = models.CharField(max_length=256, null=True, blank=True, help_text=_('Optional serial number'))
    location = models.CharField(max_length=256, null=True, blank=True, help_text=_('Optional location information'))
    install_date = models.DateField(null=True, blank=True, help_text=_('Optional install date'))
    date_acceptance = models.DateField(
        verbose_name=_("Acceptance date"),
        help_text=_('Changing acceptance date will delete unit available times that occur before it'),
    )
    active = models.BooleanField(default=True, help_text=_('Set to false if unit is no longer in use'))
    # restricted = models.BooleanField(default=False, help_text=_('Set to false to restrict unit from operation'))
    is_serviceable = models.BooleanField(
        default=True, help_text=_('Set to true to enable this unit to be selectable in service events')
    )

    modalities = models.ManyToManyField(Modality)

    class Meta:
        ordering = [settings.ORDER_UNITS_BY]

    def __str__(self):
        return self.name

    def get_potential_time(self, date_from, date_to):

        if date_from is None:
            date_from = self.date_acceptance

        elif date_from < self.date_acceptance:
            if date_to < self.date_acceptance:
                return 0
            date_from = self.date_acceptance

        self_uat_set = self.unitavailabletime_set.filter(
            date_changed__range=[date_from, date_to]
        ).order_by('date_changed')
        self_uate_set = self.unitavailabletimeedit_set.filter(
            date__range=[date_from, date_to]
        ).order_by('date')

        if self.unitavailabletime_set.filter(date_changed__lte=date_from).exists():
            latest_uat = self.unitavailabletime_set.filter(
                date_changed__lte=date_from
            ).order_by('-date_changed').latest()
            self_uat_set = self_uat_set | self.unitavailabletime_set.filter(id=latest_uat.id)

        potential_time = 0

        uate_list = {str(uate.date): uate.hours for uate in self_uate_set}

        val_list = self_uat_set.values(
            'date_changed', 'hours_sunday', 'hours_monday', 'hours_tuesday',
            'hours_wednesday', 'hours_thursday', 'hours_friday',
            'hours_saturday',
        )

        val_list_len = len(val_list)
        for i in range(val_list_len):
            next_date = val_list[i + 1]['date_changed'] - timedelta(days=1) if i < val_list_len - 1 else date_to
            this_date = date_from if val_list[i]['date_changed'] < date_from else val_list[i]['date_changed']

            days_nums = weekday_count(this_date, next_date, uate_list)

            for day in days_nums:
                potential_time += days_nums[day] * val_list[i]['hours_' + day].total_seconds()

        for uate in uate_list:
            potential_time += uate_list[uate].total_seconds()

        return potential_time / 3600


class UnitAvailableTimeEdit(models.Model):
    """
    A one off change to unit available time (holiday's, extended hours for a single day, etc)
    """
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)

    name = models.CharField(max_length=64, help_text=_('A quick name or reason for the change'), blank=True, null=True)
    date = models.DateField(help_text=_('Date of available time change'))
    hours = models.DurationField(help_text=_('New duration of availability'))

    class Meta:
        ordering = ['-date']
        get_latest_by = 'date'
        unique_together = [('unit', 'date')]
        default_permissions = ()

    def __str__(self):
        return '%s (%s)' % (self.name, self.date.strftime('%b %d, %Y'))


class UnitAvailableTime(models.Model):

    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)

    date_changed = models.DateField(blank=True, help_text=_('Date the units available time changed or will change'))
    hours_sunday = models.DurationField(help_text=_('Duration of available time on Sundays'))
    hours_monday = models.DurationField(help_text=_('Duration of available time on Mondays'))
    hours_tuesday = models.DurationField(help_text=_('Duration of available time on Tuesdays'))
    hours_wednesday = models.DurationField(help_text=_('Duration of available time on Wednesdays'))
    hours_thursday = models.DurationField(help_text=_('Duration of available time on Thursdays'))
    hours_friday = models.DurationField(help_text=_('Duration of available time on Fridays'))
    hours_saturday = models.DurationField(help_text=_('Duration of available time on Saturdays'))

    class Meta:
        ordering = ['-date_changed']
        default_permissions = ('change',)
        get_latest_by = 'date_changed'
        unique_together = [('unit', 'date_changed')]

    def __str__(self):
        return 'Available time schedule change'

    @staticmethod
    def available_times_on_unit_acceptance(unit_id):
        unit = Unit.objects.get(pk=unit_id)
        try:
            uat = UnitAvailableTime.objects.get(unit=unit, date_changed=unit.date_acceptance)
        except models.ObjectDoesNotExist:
            kwargs = {'unit': unit, 'date_changed': unit.date_acceptance}
            for d in settings.DEFAULT_AVAILABLE_TIMES:
                kwargs[d] = settings.DEFAULT_AVAILABLE_TIMES[d]
            uat = UnitAvailableTime(**kwargs)

qatrack/api/units/views.py
from rest_framework import viewsets
from rest_framework.filters import OrderingFilter
from rest_framework_filters import backends

from qatrack.api.serializers import MultiSerializerMixin
from qatrack.api.units import filters, serializers
from qatrack.units import models


class UnitViewSet(viewsets.ReadOnlyModelViewSet, MultiSerializerMixin):
    queryset = models.Unit.objects.all().order_by('number')
    serializer_class = serializers.UnitSerializer
    action_serializers = {
        'list': serializers.UnitListSerializer,
    }
    filter_class = filters.UnitFilter
    filter_backends = (backends.DjangoFilterBackend, OrderingFilter,)


class VendorViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = models.Vendor.objects.all().order_by('name')
    serializer_class = serializers.VendorSerializer
    filter_class = filters.VendorFilter
    filter_backends = (backends.DjangoFilterBackend, OrderingFilter,)


class UnitClassViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = models.UnitClass.objects.all().order_by('name')
    serializer_class = serializers.UnitClassSerializer
    filter_class = filters.UnitClassFilter
    filter_backends = (backends.DjangoFilterBackend, OrderingFilter,)


class UnitTypeViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = models.UnitType.objects.all().order_by('name')
    serializer_class = serializers.UnitClassSerializer
    filter_class = filters.UnitFilter
    filter_backends = (backends.DjangoFilterBackend, OrderingFilter,)


class ModalityViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = models.Modality.objects.all().order_by('name')
    serializer_class = serializers.ModalitySerializer
    filter_class = filters.ModalityFilter
    filter_backends = (backends.DjangoFilterBackend, OrderingFilter,)


class SiteViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = models.Site.objects.all().order_by('name')
    serializer_class = serializers.SiteSerializer
    filter_class = filters.SiteFilter
    filter_backends = (backends.DjangoFilterBackend, OrderingFilter,)


class UnitAvailableTimeViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = models.UnitAvailableTime.objects.all().order_by('unit__number', "-date_changed")
    serializer_class = serializers.UnitAvailableTimeSerializer
    filter_class = filters.UnitAvailableTimeFilter
    filter_backends = (backends.DjangoFilterBackend, OrderingFilter,)


class UnitAvailableTimeEditViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = models.UnitAvailableTimeEdit.objects.all().order_by('unit__number', "-date")
    serializer_class = serializers.UnitAvailableTimeEditSerializer
    filter_class = filters.UnitAvailableTimeEditFilter
    filter_backends = (backends.DjangoFilterBackend, OrderingFilter,)

qatrack/units/templates/units/table_context_u_actions.html
{% load qa_tags %}
{#<a class="btn btn-primary btn-xs btn-flat" href="{% url 'sl_edit' se.pk %}{% if next %}?next={{ next }}{% endif %}">Edit</a>#}
{% if USE_PARTS %}
    <a class="btn btn-default btn-xs btn-flat" href="{% url 'parts_units_cost' u.pk %}">Parts Cost</a>
    <a class="btn btn-default btn-xs btn-flat" href="{% url 'unit_available_time' u.pk %}">Available Time</a>
{% endif %}

qatrack/units/templates/units/table_context_v_actions.html
TODO

qatrack/units/templates/units/units_list.html
{% extends "service_log/sl_base.html" %}

{% load qa_tags %}
{% load listable %}

{% block head_title %}{{page_title}}{% endblock %}

{% block extra_css %}
    {{ block.super }}
    <link href="{{ STATIC_URL }}datepicker/css/bootstrap-datepicker.min.css?v={{VERSION}}" rel="stylesheet">
    <link href="{{ STATIC_URL }}multiselect/css/bootstrap.multiselect.css?v={{VERSION}}" rel="stylesheet">
    <link href="{{ STATIC_URL }}daterangepicker/css/daterangepicker.css?v={{VERSION}}" rel="stylesheet">
    <link href="{{ STATIC_URL }}qatrack_core/css/tables.css?v={{VERSION}}" rel="stylesheet">
    <link href="{{ STATIC_URL }}qatrack_core/css/custom-daterangepicker.css?v={{VERSION}}" rel="stylesheet">
{% endblock extra_css %}

{% block extra_js %}
    {% autoescape off %}
        {% listable view_name dom="<'row'<'col-sm-5'i><'col-sm-7'p>><'row'<'col-sm-12'tr>><'row'<'col-sm-5'><'col-sm-7'p>>" requirejs=True pagination_type='bootstrap3' css_table_class='table-hover table-condensed table-custom-listable' css_input_class='btn-flat btn-sm input-sm full-width' auto_width=False %}
    {% endautoescape %}
{% endblock %}

{% block require_javascript %}
    require(['listable', 'parts_reporting', 'unit_list']);
{% endblock require_javascript %}

{% block body %}

    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header">
                    <i class="fa {{ icon }} fa-fw" aria-hidden="true"></i>
                    <h3 class="box-title">{{page_title}}</h3>

                </div>
                <div class="box-body pad">
                    <div class="row">
                        <div class="col-md-12">
                            For units selected below...
                        </div>
                        <div class="col-md-12 margin-bottom-20">
                            <span id="parts_units_cost_summary" class="btn btn-info btn-flat btn-sm">Parts Costs Reports</span>
                            {% if perms.units.change_unitavailabletime %}
                                <span id="units_change_available_time" class="btn btn-info btn-flat btn-sm">Change Available Times</span>
                            {% endif %}
                        </div>
                    </div>
                    {{ listable_table }}
                </div>
            </div>
        </div>
    </div>

{% endblock body %}

qatrack/units/templates/units/unittype_choose_for_review.html
{% extends "site_base.html" %}

{% block require_javascript %}
{% endblock require_javascript %}

{% block head_title %}Choose Unit for Review{% endblock %}

{% block body %}

    {% if not split_sites %}
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header">
                        <i class="fa fa-cube" aria-hidden="true"></i>
                        <h3 class="box-title">Review QA By Unit</h3>
                        <p>Choose a unit below to review its QA Data.</p>
                    </div>
                    <div class="box-body unit-btns">

                        {% for unit_type, units in unit_types %}
                            <div class="row">
                                <div class="col-sm-12">
                                    <h4 class="header-spacer">{{unit_type}}</h4>
                                    <div class="btn-group btn-default btn-flat">
                                        {% if units|length > 1 %}
                                            <a class="btn btn-default btn-flat" href="{% url 'choose_review_unit' %}{% for unit in units %}{{unit.unit__number}}/{%endfor%}">All</a>
                                        {% endif %}

                                        {% for unit in units %}
                                            <a class="btn btn-default btn-flat" href="{% url 'review_by_unit' unit_number=unit.unit__number %}">{{unit.unit__name}}</a></button>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        {% endfor %}

                    </div>
                    <div class="box-footer"></div>
                </div>
            </div>
        </div>
    {% else %}
        <div class="row">
                <div class="col-sm-12">
                    <h4><i class="fa fa-cube" aria-hidden="true"></i>Review QA By Unit</h4>
                    <p>Choose a unit below to review its QA Data.</p>
                </div>
            </div>
            <div class="row">
                {% for site, types in unit_types.items %}
                    <div class="col-md-{{ split_by }}">
                        <div class="box">
                            <div class="box-header">
                                <h3 class="box-title">{% if site == 'zzzNonezzz' %}Other{% else %}{{ site }}{% endif %}</h3>
                            </div>
                            <div class="box-body unit-btns">
                                {% for type, units in types %}

                                    <div class="row">
                                        <div class="col-sm-12">

                                            <h4 class="header-spacer">{{ type }}</h4>
                                            {% if units|length > 1 %}
                                                <a class="btn btn-default btn-flat" href="{% url 'choose_review_unit' %}{% for unit in units %}{{unit.unit__number}}/{%endfor%}">All</a>
                                            {% endif %}
                                            {% for unit in units %}
                                                <a class="btn btn-default btn-flat" href="{% url 'review_by_unit' unit_number=unit.unit__number %}">{{unit.unit__name}}</a>
                                            {% endfor %}
                                        </div>
                                    </div>

                                {% endfor %}
                            </div>
                            <div class="box-footer"></div>
                        </div>
                    </div>

                {% endfor %}
            </div>
    {% endif %}

{% endblock %}

qatrack/units/templates/units/unittype_choose_for_service_event.html
{% extends "service_log/sl_base.html" %}
{#{% load staticfiles %}#}
{% block require_javascript %}
{#    require(['report']);#}
{% endblock require_javascript %}

{% block head_title %}Choose Unit{% endblock %}

{% block body %}


        {% if not split_sites %}
            <div class="row">
                <div class="col-md-12">
                    <div class="box">
                        <div class="box-header">
                            <i class="fa fa-cube" aria-hidden="true"></i>
                            <h3 class="box-title">
                              {% if new_se %}
                                Choose a Unit to Create a New Service Event for
                              {% else %}
                                Choose a Unit to View Service Events for
                              {% endif %}
                            </h3>
                            <p>
                              {% if new_se %}
                                Click a button to create a service event for one of the units below.
                              {% else %}
                                Click a button to view service events for one of the units below.
                              {% endif %}
                            </p>
                        </div>
                        <div class="box-body unit-btns">
                            {% for unit_type, units in unit_types%}
                                <div class="row">
                                    <div class="col-sm-12">
                                        <h4 class="header-spacer">{{unit_type}}</h4>
                                        {% for unit in units %}
                                            <a class="btn btn-default btn-flat"
                                               href="{% if new_se %}{% url "sl_new" %}?u={{ unit.unit__id }}{% else %}{% url 'sl_list_by_unit' unit_number=unit.unit__number %}">{{unit.unit__name}}{% endif %}</a>
                                        {% endfor %}
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="box-footer"></div>
                    </div>
                </div>
            </div>
        {% else %}
            <div class="row">
                <div class="col-md-12">
                    <h4>
                      <i class="fa fa-cube" aria-hidden="true"></i>
                      {% if new_se %}
                        Choose a Unit to Create a New Service Event for
                      {% else %}
                        Choose a Unit to View Service Events for
                      {% endif %}
                    </h4>
                    <p>
                      {% if new_se %}
                        Click a button to create a service event for one of the units below.
                      {% else %}
                        Click a button to view service events for one of the units below.
                      {% endif %}
                    </p>
                </div>
            </div>
            <div class="row">
                {% for site, types in unit_types.items %}
                    <div class="col-md-{{ split_by }}">
                        <div class="box">
                            <div class="box-header">
                                <h3 class="box-title">{% if site == 'zzzNonezzz' %}Other{% else %}{{ site }}{% endif %}</h3>
                            </div>
                            <div class="box-body unit-btns">
                                {% for type, units in types %}

                                    <div class="row">
                                        <div class="col-sm-12">

                                            <h4 class="header-spacer">{{ type }}</h4>
                                            {% for unit in units %}
                                            <a class="btn btn-default btn-flat" href="{% if new_se %}{% url "sl_new" %}?u={{ unit.unit__id }}{% else %}{% url 'sl_list_by_unit' unit_number=unit.unit__number %}{% endif %}">{{unit.unit__name}}</a>
                                            {% endfor %}
                                        </div>
                                    </div>

                                {% endfor %}
                            </div>
                            <div class="box-footer"></div>
                        </div>
                    </div>

                {% endfor %}
            </div>

        {% endif %}
{% endblock %}

qatrack/units/templates/units/vendors_list.html
{% extends "service_log/sl_base.html" %}

{% load qa_tags %}
{% load listable %}

{% block head_title %}{{page_title}}{% endblock %}

{% block extra_css %}
    {{ block.super }}
    <link href="{{ STATIC_URL }}datepicker/css/bootstrap-datepicker.min.css?v={{VERSION}}" rel="stylesheet">
    <link href="{{ STATIC_URL }}multiselect/css/bootstrap.multiselect.css?v={{VERSION}}" rel="stylesheet">
    <link href="{{ STATIC_URL }}daterangepicker/css/daterangepicker.css?v={{VERSION}}" rel="stylesheet">
    <link href="{{ STATIC_URL }}qatrack_core/css/tables.css?v={{VERSION}}" rel="stylesheet">
    <link href="{{ STATIC_URL }}qatrack_core/css/custom-daterangepicker.css?v={{VERSION}}" rel="stylesheet">
{% endblock extra_css %}

{% block extra_js %}
    {% autoescape off %}
        {% listable view_name dom="<'row'<'col-sm-5'i><'col-sm-7'p>><'row'<'col-sm-12'tr>><'row'<'col-sm-5'><'col-sm-7'p>>" requirejs=True pagination_type='bootstrap3' css_table_class='table-hover table-condensed table-striped' css_input_class='btn-flat btn-sm input-sm full-width' auto_width=False %}
    {% endautoescape %}
{% endblock %}

{% block require_javascript %}
    require(['listable', 'sidebar']);
{% endblock require_javascript %}

{% block body %}

    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header">
                    <i class="fa {{ icon }} fa-fw" aria-hidden="true"></i>
                    <h3 class="box-title">{{page_title}}</h3>

                </div>
                <div class="box-body pad">
                    {{ listable_table }}
                </div>
            </div>
        </div>
    </div>

{% endblock body %}